// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_mento_mentee/test/unit/request_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_mento_mentee/infrastructure/api/request_api.dart'
    as _i3;
import 'package:flutter_mento_mentee/infrastructure/models/mentor/create_mentorship_request.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCreateMentorshipRequest_0 extends _i1.SmartFake
    implements _i2.CreateMentorshipRequest {
  _FakeCreateMentorshipRequest_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFetchedMentorshipRequest_1 extends _i1.SmartFake
    implements _i2.FetchedMentorshipRequest {
  _FakeFetchedMentorshipRequest_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RequestApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestApi extends _i1.Mock implements _i3.RequestApi {
  MockRequestApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CreateMentorshipRequest> sendRequest(
    _i2.CreateMentorshipRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [request]),
            returnValue: _i4.Future<_i2.CreateMentorshipRequest>.value(
              _FakeCreateMentorshipRequest_0(
                this,
                Invocation.method(#sendRequest, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.CreateMentorshipRequest>);

  @override
  _i4.Future<List<_i2.FetchedMentorshipRequest>> getAllRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRequests, []),
            returnValue: _i4.Future<List<_i2.FetchedMentorshipRequest>>.value(
              <_i2.FetchedMentorshipRequest>[],
            ),
          )
          as _i4.Future<List<_i2.FetchedMentorshipRequest>>);

  @override
  _i4.Future<bool> deleteRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRequest, [requestId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.FetchedMentorshipRequest> updateRequest(
    String? requestId,
    _i2.UpdateMentorshipRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRequest, [requestId, request]),
            returnValue: _i4.Future<_i2.FetchedMentorshipRequest>.value(
              _FakeFetchedMentorshipRequest_1(
                this,
                Invocation.method(#updateRequest, [requestId, request]),
              ),
            ),
          )
          as _i4.Future<_i2.FetchedMentorshipRequest>);

  @override
  _i4.Future<List<_i2.FetchedMentorshipRequest>>
  getAllRequestsSentByMentees() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRequestsSentByMentees, []),
            returnValue: _i4.Future<List<_i2.FetchedMentorshipRequest>>.value(
              <_i2.FetchedMentorshipRequest>[],
            ),
          )
          as _i4.Future<List<_i2.FetchedMentorshipRequest>>);

  @override
  _i4.Future<_i2.FetchedMentorshipRequest> updateRequestStatus(
    String? requestId,
    _i2.UpdateMentorshipStatus? statusUpdate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRequestStatus, [requestId, statusUpdate]),
            returnValue: _i4.Future<_i2.FetchedMentorshipRequest>.value(
              _FakeFetchedMentorshipRequest_1(
                this,
                Invocation.method(#updateRequestStatus, [
                  requestId,
                  statusUpdate,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.FetchedMentorshipRequest>);

  @override
  _i4.Future<List<_i2.FetchedMentorshipRequest>>
  getAcceptedRequestsForMentees() =>
      (super.noSuchMethod(
            Invocation.method(#getAcceptedRequestsForMentees, []),
            returnValue: _i4.Future<List<_i2.FetchedMentorshipRequest>>.value(
              <_i2.FetchedMentorshipRequest>[],
            ),
          )
          as _i4.Future<List<_i2.FetchedMentorshipRequest>>);
}
